"""Verdict card: turn a probe run into a share-friendly "did my relay pass?" card.

The card is the tool's *social* surface. A full run prints a technical report;
``--card`` distills the same signals into a single, screenshot-able verdict so a
user can answer one question at a glance:

    Is the endpoint I pay for behaving like the model it claims?

Design rules that are non-negotiable here:

* **Signals, not proof.** The hero word is PASS / SUSPICIOUS, but every surface
  repeats that these are heuristic signals. A card is a smoke test, not a verdict
  in the legal sense.
* **Key safety is inherited.** Nothing new touches the key; every string that can
  reach a file or the screen goes through :func:`redaction.redact`.
* **Do not out the provider by default.** A card is meant to be shared. Naming the
  relay you tested would turn a private mirror into a public accusation, so the
  endpoint host is masked unless the user explicitly opts in with
  ``--card-show-endpoint``. Point the tool at whoever you like; the *card* stays
  about "an endpoint I pay for", not "vendor X is cheating".
* **Neutral signature only.** The footer credits the open-source tool and, as a
  disclosed aside, the team behind it (daoxe). No metrics, no claims, no pitch.

Rendering is pure standard library (string building). PNG export is optional and
best-effort (see :func:`to_png`); it never becomes a runtime dependency.
"""

from __future__ import annotations

import dataclasses
import html as _html
from typing import Any, Dict, List, Optional, Tuple

from . import __version__
from .redaction import redact
from .signals import Signal, CONSISTENT, SUSPICIOUS, INCONCLUSIVE

# --- Verdict tiers ----------------------------------------------------------
PASS = "PASS"
REVIEW = "REVIEW"
SUSPICIOUS_V = "SUSPICIOUS"
INCONCLUSIVE_V = "INCONCLUSIVE"

_SUBLINE = {
    PASS: "No downgrade signals in this run.",
    REVIEW: "Only low-confidence flags \u2014 re-run to confirm.",
    SUSPICIOUS_V: "Hard to explain if the claim were true.",
    INCONCLUSIVE_V: "Not enough signal (mostly errors).",
}

# The one place daoxe is mentioned: a disclosed, neutral signature (no metrics).
DAOXE_UTM = ("https://daoxe.com/?utm_source=verdict_card&utm_medium=ugc"
             "&utm_campaign=verify_your_relay")
REPO_URL = "https://github.com/seven7763/llm-honesty-probe"
CTA_HEADLINE = "Test the endpoint YOU pay for"
CTA_COMMAND = ("python3 -m llm_honesty_probe --base-url <your-endpoint> "
               "--claimed-model <model> --card")
SIGNATURE = "Generated by llm-honesty-probe \u00b7 open-source \u00b7 provider-neutral \u00b7 signals, not proof"
DISCLOSURE = "Built by the team behind daoxe \u2014 point it at us too: daoxe.com"
# Shorter variants for the fixed-width ASCII card.
SIGNATURE_TXT = "llm-honesty-probe \u00b7 open-source \u00b7 signals, not proof"
DISCLOSURE_TXT = "Built by the team behind daoxe \u2014 verify us too: daoxe.com"

# Card row order and human labels. These are the four headline signal groups the
# card is built around; ``identity`` is shown as a muted, explicitly-spoofable
# footnote row because on its own it proves nothing.
_ROW_SPEC: List[Tuple[str, str]] = [
    ("tokenizer", "Tokenizer fingerprint"),
    ("reasoning", "Capability floor"),
    ("needle", "Long context"),
    ("consistency", "Consistency"),
]
_IDENTITY_SPEC = ("identity", "Self-report")

# Fallback one-liners when a group has no usable detail string.
_FALLBACK_DETAIL = {
    ("tokenizer", CONSISTENT): "Token fingerprint matches the claimed family.",
    ("tokenizer", SUSPICIOUS): "Token fingerprint differs from the claimed model.",
    ("tokenizer", INCONCLUSIVE): "No verdict \u2014 add --compare for a definitive check.",
    ("reasoning", CONSISTENT): "Passed the easy reasoning / format floor tasks.",
    ("reasoning", SUSPICIOUS): "Failed easy tasks a full-tier model rarely misses.",
    ("reasoning", INCONCLUSIVE): "Could not grade the reasoning floor.",
    ("needle", CONSISTENT): "Recalled a hidden needle across long context.",
    ("needle", SUSPICIOUS): "Lost a needle in long context (possible truncation).",
    ("needle", INCONCLUSIVE): "Could not test long-context recall.",
    ("consistency", CONSISTENT): "Stable model id and deterministic replies.",
    ("consistency", SUSPICIOUS): "Unstable model id / routed across backends.",
    ("consistency", INCONCLUSIVE): "Not enough successful calls to judge.",
    ("identity", CONSISTENT): "Names the claimed family (easily spoofed).",
    ("identity", SUSPICIOUS): "Self-reports a different model (spoofable both ways).",
    ("identity", INCONCLUSIVE): "No clear self-report.",
}

_CONF_RANK = {"high": 3, "medium": 2, "low": 1, None: 0, "": 0}


@dataclasses.dataclass
class Row:
    key: str
    label: str
    verdict: str          # CONSISTENT / SUSPICIOUS / INCONCLUSIVE
    confidence: str
    detail: str


@dataclasses.dataclass
class Card:
    verdict: str          # PASS / REVIEW / SUSPICIOUS / INCONCLUSIVE
    subline: str
    claimed_model: str
    endpoint: str
    mode: str
    rows: List[Row]
    identity: Optional[Row]
    counts: Dict[str, int]


# --- Aggregation ------------------------------------------------------------
def _informational(sig: Signal) -> bool:
    """Latency/error-rate is informational only; it must not sway a verdict."""
    return sig.probe == "consistency" and sig.title.lower().startswith("latency")


def _pick(signals: List[Signal], probe: str) -> Optional[Row]:
    group = [s for s in signals if s.probe == probe and not _informational(s)]
    if not group:
        return None
    label = dict(_ROW_SPEC + [_IDENTITY_SPEC]).get(probe, probe.title())

    suspicious = [s for s in group if s.verdict == SUSPICIOUS]
    consistent = [s for s in group if s.verdict == CONSISTENT]

    if suspicious:
        lead = max(suspicious, key=lambda s: _CONF_RANK.get(s.confidence, 0))
        verdict = SUSPICIOUS
    elif consistent:
        lead = max(consistent, key=lambda s: _CONF_RANK.get(s.confidence, 0))
        verdict = CONSISTENT
    else:
        lead = group[0]
        verdict = INCONCLUSIVE

    # Keep card details concise: use the probe's own line when it's short and
    # punchy, otherwise fall back to a crafted one-liner.
    raw = redact((lead.detail or "").strip())
    fallback = _FALLBACK_DETAIL.get((probe, verdict), "")
    if probe == "identity":
        # The self-report line is a muted footnote; keep only the first clause
        # ("Claimed gpt but self-reports llama") and drop the verbose caveats.
        first = raw.split(". ")[0].strip() if raw else ""
        detail = first if 0 < len(first) <= 60 else (fallback or raw)
    else:
        detail = raw if (raw and len(raw) <= 72) else (fallback or raw)
    return Row(key=probe, label=label, verdict=verdict,
               confidence=lead.confidence, detail=detail)


def _overall(rows: List[Row], identity: Optional[Row]) -> str:
    all_rows = rows + ([identity] if identity else [])
    strong = any(r.verdict == SUSPICIOUS and _CONF_RANK.get(r.confidence, 0) >= 2
                 for r in all_rows)
    weak = any(r.verdict == SUSPICIOUS for r in all_rows)
    consistent = any(r.verdict == CONSISTENT for r in rows)
    if strong:
        return SUSPICIOUS_V
    if weak:
        return REVIEW
    if consistent:
        return PASS
    return INCONCLUSIVE_V


def _mask_endpoint(meta: Dict[str, Any], show: bool) -> str:
    mode = str(meta.get("mode", ""))
    if "self-test" in mode:
        return "built-in self-test mock"
    raw = redact(str(meta.get("base_url", "")))
    if not raw:
        return "your endpoint (hidden)"
    if show:
        return raw
    scheme = raw.split("://", 1)[0] if "://" in raw else ""
    prefix = (scheme + "://") if scheme else ""
    return "%s\u2022\u2022\u2022 (hidden \u2014 safe to share)" % prefix


def build_card(signals: List[Signal], meta: Dict[str, Any],
               show_endpoint: bool = False) -> Card:
    rows: List[Row] = []
    for probe, _label in _ROW_SPEC:
        row = _pick(signals, probe)
        if row is None:
            row = Row(key=probe, label=dict(_ROW_SPEC)[probe],
                      verdict=INCONCLUSIVE, confidence="low",
                      detail=_FALLBACK_DETAIL.get((probe, INCONCLUSIVE), "Not tested."))
        rows.append(row)
    identity = _pick(signals, _IDENTITY_SPEC[0])
    if identity is not None:
        identity.label = _IDENTITY_SPEC[1]

    verdict = _overall(rows, identity)
    counts = {CONSISTENT: 0, SUSPICIOUS: 0, INCONCLUSIVE: 0}
    for r in rows + ([identity] if identity else []):
        counts[r.verdict] = counts.get(r.verdict, 0) + 1

    return Card(
        verdict=verdict,
        subline=_SUBLINE[verdict],
        claimed_model=redact(str(meta.get("claimed_model", "") or "unknown")),
        endpoint=_mask_endpoint(meta, show_endpoint),
        mode=str(meta.get("mode", "single-endpoint")),
        rows=rows,
        identity=identity,
        counts=counts,
    )


# --- Marks / palette --------------------------------------------------------
_ASCII_MARK = {CONSISTENT: "[+]", SUSPICIOUS: "[!]", INCONCLUSIVE: "[-]"}
_GLYPH_MARK = {CONSISTENT: "\u2713", SUSPICIOUS: "\u2717", INCONCLUSIVE: "\u2013"}

_COLOR = {
    PASS: "#22c55e",
    REVIEW: "#f59e0b",
    SUSPICIOUS_V: "#ef4444",
    INCONCLUSIVE_V: "#64748b",
}
_ROW_COLOR = {CONSISTENT: "#22c55e", SUSPICIOUS: "#ef4444", INCONCLUSIVE: "#64748b"}

_BG = "#0b1220"
_PANEL = "#111c33"
_TEXT = "#e6edf6"
_MUTED = "#93a4bd"
_BORDER = "#22304a"
_CODEBG = "#0a1526"


def _conf_tag(row: Row) -> str:
    if row.verdict == SUSPICIOUS and row.confidence:
        return " (%s)" % row.confidence
    return ""


# --- ASCII / text -----------------------------------------------------------
def _wrap(text: str, width: int) -> List[str]:
    words = text.split()
    lines: List[str] = []
    cur = ""
    for w in words:
        if len(w) > width:
            if cur:
                lines.append(cur)
                cur = ""
            while len(w) > width:
                lines.append(w[:width])
                w = w[width:]
            cur = w
            continue
        if not cur:
            cur = w
        elif len(cur) + 1 + len(w) <= width:
            cur += " " + w
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def render_text(card: Card, width: int = 74) -> str:
    inner = width - 2
    out: List[str] = []

    def rule(left: str, fill: str, right: str) -> None:
        out.append(left + fill * inner + right)

    def line(text: str = "") -> None:
        out.append("|" + text[:inner].ljust(inner) + "|")

    rule("+", "-", "+")
    line(" LLM HONESTY PROBE \u00b7 verdict card" + ("v%s" % __version__).rjust(
        inner - len(" LLM HONESTY PROBE \u00b7 verdict card")))
    rule("+", "-", "+")
    line()
    banner = "  ===  %s  ===" % card.verdict
    line(banner)
    line("  " + card.subline)
    line()
    line("  claimed model : %s" % card.claimed_model)
    line("  endpoint      : %s" % card.endpoint)
    line()
    for row in card.rows:
        line("  %s %s" % (_ASCII_MARK.get(row.verdict, "[?]"), row.label))
        for seg in _wrap(row.detail + _conf_tag(row), inner - 8):
            line("        " + seg)
    if card.identity:
        r = card.identity
        line("  %s %s (spoofable, low weight)" % (
            _ASCII_MARK.get(r.verdict, "[?]"), r.label))
        for seg in _wrap(r.detail + _conf_tag(r), inner - 8):
            line("        " + seg)
    line()
    line("  -> %s:" % CTA_HEADLINE)
    line("     python3 -m llm_honesty_probe \\")
    line("       --base-url <your-endpoint> --claimed-model <model> --card")
    line()
    rule("+", "-", "+")
    line("  " + SIGNATURE_TXT)
    line("  " + DISCLOSURE_TXT)
    rule("+", "-", "+")
    return "\n".join(out)


# --- Markdown (forum paste) -------------------------------------------------
def render_markdown(card: Card) -> str:
    out: List[str] = []
    out.append("```")
    out.append(render_text(card))
    out.append("```")
    out.append("")
    out.append("**Verdict: %s** \u2014 %s" % (card.verdict, card.subline))
    out.append("")
    out.append("| Signal | Result |")
    out.append("|---|---|")
    for row in card.rows:
        mark = _GLYPH_MARK.get(row.verdict, "?")
        out.append("| %s %s | %s%s |" % (mark, row.label,
                                         row.detail.replace("|", "\\|"), _conf_tag(row)))
    if card.identity:
        r = card.identity
        out.append("| %s %s | %s%s |" % (_GLYPH_MARK.get(r.verdict, "?"), r.label,
                                         r.detail.replace("|", "\\|"), _conf_tag(r)))
    out.append("")
    out.append("> These are **heuristic signals, not proof.** "
               "Test the endpoint *you* pay for \u2014 it's one command, your key never "
               "leaves your machine: %s" % REPO_URL)
    return "\n".join(out)


# --- SVG (image, screenshot / embed) ---------------------------------------
_SVG_SUBST = {
    "\u2014": "-", "\u2013": "-", "\u2026": "...", "\u2192": ">",
    "\u2022": "*", "\u2713": "v", "\u2717": "x",
}


def _svg_safe(s: str) -> str:
    """Replace glyphs a headless SVG rasterizer's fonts may lack with ASCII."""
    for bad, good in _SVG_SUBST.items():
        s = s.replace(bad, good)
    return s


def _xml(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def _svg_text(x: int, y: int, s: str, size: int, color: str, *,
              weight: str = "normal", mono: bool = False, anchor: str = "start",
              opacity: float = 1.0) -> str:
    family = ("ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" if mono
              else "-apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif")
    return ('<text x="%d" y="%d" font-family="%s" font-size="%d" font-weight="%s" '
            'fill="%s" text-anchor="%s" fill-opacity="%s">%s</text>'
            % (x, y, family, size, weight, color, anchor, opacity, _xml(_svg_safe(s))))


def _icon(cx: int, cy: int, verdict: str, color: str, r: int = 14) -> str:
    """Draw a status icon as vector paths (font-independent)."""
    out = ['<circle cx="%d" cy="%d" r="%d" fill="%s"/>' % (cx, cy, r, color)]
    dark = "#0b1220"
    if verdict == CONSISTENT:  # check mark
        out.append('<path d="M%d %d L%d %d L%d %d" fill="none" stroke="%s" '
                   'stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>'
                   % (cx - 6, cy, cx - 2, cy + 4, cx + 6, cy - 5, dark))
    elif verdict == SUSPICIOUS:  # exclamation
        out.append('<rect x="%d" y="%d" width="3" height="8" rx="1.5" fill="%s"/>'
                   % (cx - 1, cy - 6, dark))
        out.append('<circle cx="%d" cy="%d" r="2" fill="%s"/>' % (cx, cy + 5, dark))
    else:  # inconclusive: dash
        out.append('<rect x="%d" y="%d" width="12" height="3" rx="1.5" fill="%s"/>'
                   % (cx - 6, cy - 1, dark))
    return "".join(out)


def _truncate(s: str, n: int) -> str:
    s = s.strip()
    return s if len(s) <= n else s[: n - 1].rstrip() + "\u2026"


def render_svg(card: Card) -> str:
    W, H = 1200, 700
    x0 = 56
    accent = _COLOR.get(card.verdict, "#64748b")
    p: List[str] = []
    p.append('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" '
             'viewBox="0 0 %d %d">' % (W, H, W, H))
    p.append('<rect width="%d" height="%d" rx="28" fill="%s"/>' % (W, H, _BG))
    p.append('<rect x="6" y="6" width="%d" height="%d" rx="24" fill="none" '
             'stroke="%s" stroke-width="2"/>' % (W - 12, H - 12, _BORDER))
    p.append('<rect x="0" y="0" width="12" height="%d" rx="6" fill="%s"/>' % (H, accent))

    # Header.
    p.append(_svg_text(x0, 74, "LLM HONESTY PROBE", 30, _TEXT, weight="700"))
    p.append(_svg_text(W - x0, 74, "verdict card \u00b7 v%s" % __version__, 22,
                       _MUTED, anchor="end"))
    p.append('<line x1="%d" y1="98" x2="%d" y2="98" stroke="%s" stroke-width="1"/>'
             % (x0, W - x0, _BORDER))

    # Verdict pill + target details.
    pill_w = 240 + max(0, len(card.verdict) - 4) * 25
    p.append('<rect x="%d" y="124" width="%d" height="92" rx="18" fill="%s"/>'
             % (x0, pill_w, accent))
    p.append(_svg_text(x0 + pill_w // 2, 186, card.verdict, 44, "#0b1220",
                       weight="800", anchor="middle"))
    tx = x0 + pill_w + 34
    p.append(_svg_text(tx, 156, _truncate(card.subline, 46), 22, _TEXT, weight="600"))
    p.append(_svg_text(tx, 188, "claimed model:  %s" % _truncate(card.claimed_model, 30),
                       20, _MUTED))
    p.append(_svg_text(tx, 214, "endpoint:  %s" % _truncate(card.endpoint, 34), 20, _MUTED))

    # Signal rows (four headline groups).
    y = 282
    step = 60
    for row in card.rows:
        rc = _ROW_COLOR.get(row.verdict, _MUTED)
        p.append(_icon(x0 + 18, y - 6, row.verdict, rc))
        p.append(_svg_text(x0 + 48, y, row.label, 24, _TEXT, weight="700"))
        p.append(_svg_text(x0 + 48, y + 26, _truncate(row.detail + _conf_tag(row), 80),
                           19, _MUTED))
        y += step

    # Identity footnote (muted, one line).
    if card.identity:
        r = card.identity
        rc = _ROW_COLOR.get(r.verdict, _MUTED)
        p.append('<circle cx="%d" cy="%d" r="7" fill="%s" fill-opacity="0.75"/>'
                 % (x0 + 18, y - 10, rc))
        p.append(_svg_text(x0 + 48, y - 5, "self-report (spoofable): %s"
                           % _truncate(r.detail, 58), 18, _MUTED, opacity=0.9))
        y += 34

    # CTA block.
    p.append(_svg_text(x0, y + 6, "\u2192 %s" % CTA_HEADLINE, 23, accent, weight="700"))
    box_y = y + 22
    p.append('<rect x="%d" y="%d" width="%d" height="48" rx="12" fill="%s" '
             'stroke="%s" stroke-width="1"/>' % (x0, box_y, W - 2 * x0, _CODEBG, _BORDER))
    p.append(_svg_text(x0 + 20, box_y + 31, CTA_COMMAND, 18, "#c8d6ee", mono=True))

    # Footer signature (the only place daoxe appears).
    p.append('<line x1="%d" y1="%d" x2="%d" y2="%d" stroke="%s" stroke-width="1"/>'
             % (x0, H - 46, W - x0, H - 46, _BORDER))
    p.append(_svg_text(x0, H - 20, SIGNATURE, 16, _MUTED))
    p.append(_svg_text(W - x0, H - 20, "daoxe.com", 16, _MUTED, anchor="end", weight="600"))
    p.append("</svg>")
    return "".join(p)


# --- HTML (self-contained, screenshot at 2x) --------------------------------
def render_html(card: Card) -> str:
    svg = render_svg(card)
    title = "llm-honesty-probe verdict: %s" % card.verdict
    return (
        "<!doctype html>\n<html lang=\"en\">\n<head>\n"
        "<meta charset=\"utf-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "<title>%s</title>\n"
        "<style>\n"
        "  html,body{margin:0;background:#060a14;color:#93a4bd;"
        "font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif}\n"
        "  .wrap{min-height:100vh;display:flex;flex-direction:column;align-items:center;"
        "justify-content:center;gap:16px;padding:32px}\n"
        "  .card{width:1200px;max-width:96vw;height:auto;filter:drop-shadow(0 24px 60px "
        "rgba(0,0,0,.55));border-radius:28px;overflow:hidden}\n"
        "  .card svg{display:block;width:100%%;height:auto}\n"
        "  .hint{font-size:13px;opacity:.7}\n"
        "</style>\n</head>\n<body>\n<div class=\"wrap\">\n"
        "<div class=\"card\">%s</div>\n"
        "<div class=\"hint\">Screenshot the card above \u00b7 signals, not proof \u00b7 "
        "%s</div>\n</div>\n</body>\n</html>\n" % (_html.escape(title), svg, REPO_URL)
    )


# --- PNG (optional, best-effort) -------------------------------------------
def to_png(svg: str, out_path: str, scale: float = 1.0) -> Tuple[bool, str]:
    """Rasterize *svg* to *out_path*. Returns (ok, note).

    Best-effort and dependency-free by default: tries ``cairosvg`` (if the user
    happens to have it), then common CLI rasterizers. If none are present it
    returns ``(False, hint)`` so the caller can fall back to writing the SVG.
    """
    width = int(1200 * scale)
    try:
        import cairosvg  # type: ignore
        cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=out_path,
                         output_width=width)
        return True, "cairosvg"
    except Exception:  # noqa: BLE001 - fall through to CLI tools
        pass

    import shutil
    import subprocess
    import tempfile
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False,
                                     encoding="utf-8") as fh:
        fh.write(svg)
        svg_path = fh.name
    try:
        if shutil.which("rsvg-convert"):
            subprocess.run(["rsvg-convert", "-w", str(width), "-o", out_path, svg_path],
                           check=True, capture_output=True)
            return True, "rsvg-convert"
        if shutil.which("inkscape"):
            subprocess.run(["inkscape", svg_path, "--export-type=png",
                            "--export-filename=" + out_path, "-w", str(width)],
                           check=True, capture_output=True)
            return True, "inkscape"
        if shutil.which("resvg"):
            subprocess.run(["resvg", "-w", str(width), svg_path, out_path],
                           check=True, capture_output=True)
            return True, "resvg"
    except Exception as exc:  # noqa: BLE001
        return False, "rasterizer failed: %s" % exc
    finally:
        try:
            import os
            os.unlink(svg_path)
        except OSError:
            pass
    return (False, "no SVG->PNG rasterizer found (install cairosvg or rsvg-convert); "
                   "wrote .svg instead")


# --- Format dispatch --------------------------------------------------------
def render(card: Card, fmt: str) -> str:
    if fmt == "txt":
        return render_text(card)
    if fmt == "md":
        return render_markdown(card)
    if fmt == "svg":
        return render_svg(card)
    if fmt == "html":
        return render_html(card)
    raise ValueError("unknown text format %r" % fmt)
